//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BARBARES_SistemaWeb.ServiceReferenceProducto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUnidadProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PerecibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PresentacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoProducto {
            get {
                return this.IdTipoProductoField;
            }
            set {
                if ((this.IdTipoProductoField.Equals(value) != true)) {
                    this.IdTipoProductoField = value;
                    this.RaisePropertyChanged("IdTipoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUnidadProducto {
            get {
                return this.IdUnidadProductoField;
            }
            set {
                if ((this.IdUnidadProductoField.Equals(value) != true)) {
                    this.IdUnidadProductoField = value;
                    this.RaisePropertyChanged("IdUnidadProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Perecible {
            get {
                return this.PerecibleField;
            }
            set {
                if ((this.PerecibleField.Equals(value) != true)) {
                    this.PerecibleField = value;
                    this.RaisePropertyChanged("Perecible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioUnitario {
            get {
                return this.PrecioUnitarioField;
            }
            set {
                if ((this.PrecioUnitarioField.Equals(value) != true)) {
                    this.PrecioUnitarioField = value;
                    this.RaisePropertyChanged("PrecioUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Presentacion {
            get {
                return this.PresentacionField;
            }
            set {
                if ((this.PresentacionField.Equals(value) != true)) {
                    this.PresentacionField = value;
                    this.RaisePropertyChanged("Presentacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBD", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ResponseBD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlujoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flujo {
            get {
                return this.FlujoField;
            }
            set {
                if ((object.ReferenceEquals(this.FlujoField, value) != true)) {
                    this.FlujoField = value;
                    this.RaisePropertyChanged("Flujo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoProducto", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class TipoProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoProducto {
            get {
                return this.IdTipoProductoField;
            }
            set {
                if ((this.IdTipoProductoField.Equals(value) != true)) {
                    this.IdTipoProductoField = value;
                    this.RaisePropertyChanged("IdTipoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnidadProducto", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class UnidadProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUnidadProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUnidadProducto {
            get {
                return this.IdUnidadProductoField;
            }
            set {
                if ((this.IdUnidadProductoField.Equals(value) != true)) {
                    this.IdUnidadProductoField = value;
                    this.RaisePropertyChanged("IdUnidadProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unidad {
            get {
                return this.UnidadField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadField, value) != true)) {
                    this.UnidadField = value;
                    this.RaisePropertyChanged("Unidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoXAlmacen", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ProductoXAlmacen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAlmacenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoXAlmacenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((this.FechaVencimientoField.Equals(value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAlmacen {
            get {
                return this.IdAlmacenField;
            }
            set {
                if ((this.IdAlmacenField.Equals(value) != true)) {
                    this.IdAlmacenField = value;
                    this.RaisePropertyChanged("IdAlmacen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProductoXAlmacen {
            get {
                return this.IdProductoXAlmacenField;
            }
            set {
                if ((this.IdProductoXAlmacenField.Equals(value) != true)) {
                    this.IdProductoXAlmacenField = value;
                    this.RaisePropertyChanged("IdProductoXAlmacen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoXVehiculo", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ProductoXVehiculo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoXVehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdVehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((this.FechaVencimientoField.Equals(value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProductoXVehiculo {
            get {
                return this.IdProductoXVehiculoField;
            }
            set {
                if ((this.IdProductoXVehiculoField.Equals(value) != true)) {
                    this.IdProductoXVehiculoField = value;
                    this.RaisePropertyChanged("IdProductoXVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdVehiculo {
            get {
                return this.IdVehiculoField;
            }
            set {
                if ((this.IdVehiculoField.Equals(value) != true)) {
                    this.IdVehiculoField = value;
                    this.RaisePropertyChanged("IdVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProducto.IProducto_Services")]
    public interface IProducto_Services {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/selectAll_Producto", ReplyAction="http://tempuri.org/IProducto_Services/selectAll_ProductoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceProducto.Producto[] selectAll_Producto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/selectAll_Producto", ReplyAction="http://tempuri.org/IProducto_Services/selectAll_ProductoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.Producto[]> selectAll_ProductoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/add_Producto", ReplyAction="http://tempuri.org/IProducto_Services/add_ProductoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD add_Producto(BARBARES_SistemaWeb.ServiceReferenceProducto.Producto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/add_Producto", ReplyAction="http://tempuri.org/IProducto_Services/add_ProductoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD> add_ProductoAsync(BARBARES_SistemaWeb.ServiceReferenceProducto.Producto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/selectAll_TipoProducto", ReplyAction="http://tempuri.org/IProducto_Services/selectAll_TipoProductoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceProducto.TipoProducto[] selectAll_TipoProducto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/selectAll_TipoProducto", ReplyAction="http://tempuri.org/IProducto_Services/selectAll_TipoProductoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.TipoProducto[]> selectAll_TipoProductoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/add_TipoProducto", ReplyAction="http://tempuri.org/IProducto_Services/add_TipoProductoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD add_TipoProducto(BARBARES_SistemaWeb.ServiceReferenceProducto.TipoProducto t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/add_TipoProducto", ReplyAction="http://tempuri.org/IProducto_Services/add_TipoProductoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD> add_TipoProductoAsync(BARBARES_SistemaWeb.ServiceReferenceProducto.TipoProducto t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/selectAll_UnidadProducto", ReplyAction="http://tempuri.org/IProducto_Services/selectAll_UnidadProductoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceProducto.UnidadProducto[] selectAll_UnidadProducto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/selectAll_UnidadProducto", ReplyAction="http://tempuri.org/IProducto_Services/selectAll_UnidadProductoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.UnidadProducto[]> selectAll_UnidadProductoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/add_UnidadProducto", ReplyAction="http://tempuri.org/IProducto_Services/add_UnidadProductoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD add_UnidadProducto(BARBARES_SistemaWeb.ServiceReferenceProducto.UnidadProducto u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/add_UnidadProducto", ReplyAction="http://tempuri.org/IProducto_Services/add_UnidadProductoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD> add_UnidadProductoAsync(BARBARES_SistemaWeb.ServiceReferenceProducto.UnidadProducto u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/selectAll_ProductoXAlmacen", ReplyAction="http://tempuri.org/IProducto_Services/selectAll_ProductoXAlmacenResponse")]
        BARBARES_SistemaWeb.ServiceReferenceProducto.ProductoXAlmacen[] selectAll_ProductoXAlmacen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/selectAll_ProductoXAlmacen", ReplyAction="http://tempuri.org/IProducto_Services/selectAll_ProductoXAlmacenResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.ProductoXAlmacen[]> selectAll_ProductoXAlmacenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/add_ProductoXAlmacen", ReplyAction="http://tempuri.org/IProducto_Services/add_ProductoXAlmacenResponse")]
        BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD add_ProductoXAlmacen(BARBARES_SistemaWeb.ServiceReferenceProducto.ProductoXAlmacen p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/add_ProductoXAlmacen", ReplyAction="http://tempuri.org/IProducto_Services/add_ProductoXAlmacenResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD> add_ProductoXAlmacenAsync(BARBARES_SistemaWeb.ServiceReferenceProducto.ProductoXAlmacen p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/selectAll_ProductoXVehiculo", ReplyAction="http://tempuri.org/IProducto_Services/selectAll_ProductoXVehiculoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceProducto.ProductoXVehiculo[] selectAll_ProductoXVehiculo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/selectAll_ProductoXVehiculo", ReplyAction="http://tempuri.org/IProducto_Services/selectAll_ProductoXVehiculoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.ProductoXVehiculo[]> selectAll_ProductoXVehiculoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/add_ProductoXVehiculo", ReplyAction="http://tempuri.org/IProducto_Services/add_ProductoXVehiculoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD add_ProductoXVehiculo(BARBARES_SistemaWeb.ServiceReferenceProducto.ProductoXVehiculo p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto_Services/add_ProductoXVehiculo", ReplyAction="http://tempuri.org/IProducto_Services/add_ProductoXVehiculoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD> add_ProductoXVehiculoAsync(BARBARES_SistemaWeb.ServiceReferenceProducto.ProductoXVehiculo p);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProducto_ServicesChannel : BARBARES_SistemaWeb.ServiceReferenceProducto.IProducto_Services, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Producto_ServicesClient : System.ServiceModel.ClientBase<BARBARES_SistemaWeb.ServiceReferenceProducto.IProducto_Services>, BARBARES_SistemaWeb.ServiceReferenceProducto.IProducto_Services {
        
        public Producto_ServicesClient() {
        }
        
        public Producto_ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Producto_ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Producto_ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Producto_ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceProducto.Producto[] selectAll_Producto() {
            return base.Channel.selectAll_Producto();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.Producto[]> selectAll_ProductoAsync() {
            return base.Channel.selectAll_ProductoAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD add_Producto(BARBARES_SistemaWeb.ServiceReferenceProducto.Producto p) {
            return base.Channel.add_Producto(p);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD> add_ProductoAsync(BARBARES_SistemaWeb.ServiceReferenceProducto.Producto p) {
            return base.Channel.add_ProductoAsync(p);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceProducto.TipoProducto[] selectAll_TipoProducto() {
            return base.Channel.selectAll_TipoProducto();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.TipoProducto[]> selectAll_TipoProductoAsync() {
            return base.Channel.selectAll_TipoProductoAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD add_TipoProducto(BARBARES_SistemaWeb.ServiceReferenceProducto.TipoProducto t) {
            return base.Channel.add_TipoProducto(t);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD> add_TipoProductoAsync(BARBARES_SistemaWeb.ServiceReferenceProducto.TipoProducto t) {
            return base.Channel.add_TipoProductoAsync(t);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceProducto.UnidadProducto[] selectAll_UnidadProducto() {
            return base.Channel.selectAll_UnidadProducto();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.UnidadProducto[]> selectAll_UnidadProductoAsync() {
            return base.Channel.selectAll_UnidadProductoAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD add_UnidadProducto(BARBARES_SistemaWeb.ServiceReferenceProducto.UnidadProducto u) {
            return base.Channel.add_UnidadProducto(u);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD> add_UnidadProductoAsync(BARBARES_SistemaWeb.ServiceReferenceProducto.UnidadProducto u) {
            return base.Channel.add_UnidadProductoAsync(u);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceProducto.ProductoXAlmacen[] selectAll_ProductoXAlmacen() {
            return base.Channel.selectAll_ProductoXAlmacen();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.ProductoXAlmacen[]> selectAll_ProductoXAlmacenAsync() {
            return base.Channel.selectAll_ProductoXAlmacenAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD add_ProductoXAlmacen(BARBARES_SistemaWeb.ServiceReferenceProducto.ProductoXAlmacen p) {
            return base.Channel.add_ProductoXAlmacen(p);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD> add_ProductoXAlmacenAsync(BARBARES_SistemaWeb.ServiceReferenceProducto.ProductoXAlmacen p) {
            return base.Channel.add_ProductoXAlmacenAsync(p);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceProducto.ProductoXVehiculo[] selectAll_ProductoXVehiculo() {
            return base.Channel.selectAll_ProductoXVehiculo();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.ProductoXVehiculo[]> selectAll_ProductoXVehiculoAsync() {
            return base.Channel.selectAll_ProductoXVehiculoAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD add_ProductoXVehiculo(BARBARES_SistemaWeb.ServiceReferenceProducto.ProductoXVehiculo p) {
            return base.Channel.add_ProductoXVehiculo(p);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceProducto.ResponseBD> add_ProductoXVehiculoAsync(BARBARES_SistemaWeb.ServiceReferenceProducto.ProductoXVehiculo p) {
            return base.Channel.add_ProductoXVehiculoAsync(p);
        }
    }
}
