//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BARBARES_SistemaWeb.ServiceReferenceMovimiento {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movimiento", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Movimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAlmacenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdVehiculoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAlmacen {
            get {
                return this.IdAlmacenField;
            }
            set {
                if ((this.IdAlmacenField.Equals(value) != true)) {
                    this.IdAlmacenField = value;
                    this.RaisePropertyChanged("IdAlmacen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMovimiento {
            get {
                return this.IdMovimientoField;
            }
            set {
                if ((this.IdMovimientoField.Equals(value) != true)) {
                    this.IdMovimientoField = value;
                    this.RaisePropertyChanged("IdMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPedido {
            get {
                return this.IdPedidoField;
            }
            set {
                if ((this.IdPedidoField.Equals(value) != true)) {
                    this.IdPedidoField = value;
                    this.RaisePropertyChanged("IdPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoMovimiento {
            get {
                return this.IdTipoMovimientoField;
            }
            set {
                if ((this.IdTipoMovimientoField.Equals(value) != true)) {
                    this.IdTipoMovimientoField = value;
                    this.RaisePropertyChanged("IdTipoMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdVehiculo {
            get {
                return this.IdVehiculoField;
            }
            set {
                if ((this.IdVehiculoField.Equals(value) != true)) {
                    this.IdVehiculoField = value;
                    this.RaisePropertyChanged("IdVehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBD", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ResponseBD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlujoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flujo {
            get {
                return this.FlujoField;
            }
            set {
                if ((object.ReferenceEquals(this.FlujoField, value) != true)) {
                    this.FlujoField = value;
                    this.RaisePropertyChanged("Flujo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleMovimiento", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class DetalleMovimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDetalleMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoXVehiculoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDetalleMovimiento {
            get {
                return this.IdDetalleMovimientoField;
            }
            set {
                if ((this.IdDetalleMovimientoField.Equals(value) != true)) {
                    this.IdDetalleMovimientoField = value;
                    this.RaisePropertyChanged("IdDetalleMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMovimiento {
            get {
                return this.IdMovimientoField;
            }
            set {
                if ((this.IdMovimientoField.Equals(value) != true)) {
                    this.IdMovimientoField = value;
                    this.RaisePropertyChanged("IdMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProductoXVehiculo {
            get {
                return this.IdProductoXVehiculoField;
            }
            set {
                if ((this.IdProductoXVehiculoField.Equals(value) != true)) {
                    this.IdProductoXVehiculoField = value;
                    this.RaisePropertyChanged("IdProductoXVehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoMovimiento", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class TipoMovimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoMovimiento {
            get {
                return this.IdTipoMovimientoField;
            }
            set {
                if ((this.IdTipoMovimientoField.Equals(value) != true)) {
                    this.IdTipoMovimientoField = value;
                    this.RaisePropertyChanged("IdTipoMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceMovimiento.IMovimiento_Services")]
    public interface IMovimiento_Services {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento_Services/selectAll_Movimiento", ReplyAction="http://tempuri.org/IMovimiento_Services/selectAll_MovimientoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceMovimiento.Movimiento[] selectAll_Movimiento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento_Services/selectAll_Movimiento", ReplyAction="http://tempuri.org/IMovimiento_Services/selectAll_MovimientoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceMovimiento.Movimiento[]> selectAll_MovimientoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento_Services/add_Movimiento", ReplyAction="http://tempuri.org/IMovimiento_Services/add_MovimientoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceMovimiento.ResponseBD add_Movimiento(BARBARES_SistemaWeb.ServiceReferenceMovimiento.Movimiento m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento_Services/add_Movimiento", ReplyAction="http://tempuri.org/IMovimiento_Services/add_MovimientoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceMovimiento.ResponseBD> add_MovimientoAsync(BARBARES_SistemaWeb.ServiceReferenceMovimiento.Movimiento m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento_Services/selectAll_DetalleMovimiento", ReplyAction="http://tempuri.org/IMovimiento_Services/selectAll_DetalleMovimientoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceMovimiento.DetalleMovimiento[] selectAll_DetalleMovimiento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento_Services/selectAll_DetalleMovimiento", ReplyAction="http://tempuri.org/IMovimiento_Services/selectAll_DetalleMovimientoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceMovimiento.DetalleMovimiento[]> selectAll_DetalleMovimientoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento_Services/add_DetalleMovimiento", ReplyAction="http://tempuri.org/IMovimiento_Services/add_DetalleMovimientoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceMovimiento.ResponseBD add_DetalleMovimiento(BARBARES_SistemaWeb.ServiceReferenceMovimiento.DetalleMovimiento m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento_Services/add_DetalleMovimiento", ReplyAction="http://tempuri.org/IMovimiento_Services/add_DetalleMovimientoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceMovimiento.ResponseBD> add_DetalleMovimientoAsync(BARBARES_SistemaWeb.ServiceReferenceMovimiento.DetalleMovimiento m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento_Services/selectAll_TipoMovimiento", ReplyAction="http://tempuri.org/IMovimiento_Services/selectAll_TipoMovimientoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceMovimiento.TipoMovimiento[] selectAll_TipoMovimiento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento_Services/selectAll_TipoMovimiento", ReplyAction="http://tempuri.org/IMovimiento_Services/selectAll_TipoMovimientoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceMovimiento.TipoMovimiento[]> selectAll_TipoMovimientoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento_Services/add_TipoMovimiento", ReplyAction="http://tempuri.org/IMovimiento_Services/add_TipoMovimientoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceMovimiento.ResponseBD add_TipoMovimiento(BARBARES_SistemaWeb.ServiceReferenceMovimiento.TipoMovimiento m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento_Services/add_TipoMovimiento", ReplyAction="http://tempuri.org/IMovimiento_Services/add_TipoMovimientoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceMovimiento.ResponseBD> add_TipoMovimientoAsync(BARBARES_SistemaWeb.ServiceReferenceMovimiento.TipoMovimiento m);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMovimiento_ServicesChannel : BARBARES_SistemaWeb.ServiceReferenceMovimiento.IMovimiento_Services, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Movimiento_ServicesClient : System.ServiceModel.ClientBase<BARBARES_SistemaWeb.ServiceReferenceMovimiento.IMovimiento_Services>, BARBARES_SistemaWeb.ServiceReferenceMovimiento.IMovimiento_Services {
        
        public Movimiento_ServicesClient() {
        }
        
        public Movimiento_ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Movimiento_ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Movimiento_ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Movimiento_ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceMovimiento.Movimiento[] selectAll_Movimiento() {
            return base.Channel.selectAll_Movimiento();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceMovimiento.Movimiento[]> selectAll_MovimientoAsync() {
            return base.Channel.selectAll_MovimientoAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceMovimiento.ResponseBD add_Movimiento(BARBARES_SistemaWeb.ServiceReferenceMovimiento.Movimiento m) {
            return base.Channel.add_Movimiento(m);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceMovimiento.ResponseBD> add_MovimientoAsync(BARBARES_SistemaWeb.ServiceReferenceMovimiento.Movimiento m) {
            return base.Channel.add_MovimientoAsync(m);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceMovimiento.DetalleMovimiento[] selectAll_DetalleMovimiento() {
            return base.Channel.selectAll_DetalleMovimiento();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceMovimiento.DetalleMovimiento[]> selectAll_DetalleMovimientoAsync() {
            return base.Channel.selectAll_DetalleMovimientoAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceMovimiento.ResponseBD add_DetalleMovimiento(BARBARES_SistemaWeb.ServiceReferenceMovimiento.DetalleMovimiento m) {
            return base.Channel.add_DetalleMovimiento(m);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceMovimiento.ResponseBD> add_DetalleMovimientoAsync(BARBARES_SistemaWeb.ServiceReferenceMovimiento.DetalleMovimiento m) {
            return base.Channel.add_DetalleMovimientoAsync(m);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceMovimiento.TipoMovimiento[] selectAll_TipoMovimiento() {
            return base.Channel.selectAll_TipoMovimiento();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceMovimiento.TipoMovimiento[]> selectAll_TipoMovimientoAsync() {
            return base.Channel.selectAll_TipoMovimientoAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceMovimiento.ResponseBD add_TipoMovimiento(BARBARES_SistemaWeb.ServiceReferenceMovimiento.TipoMovimiento m) {
            return base.Channel.add_TipoMovimiento(m);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceMovimiento.ResponseBD> add_TipoMovimientoAsync(BARBARES_SistemaWeb.ServiceReferenceMovimiento.TipoMovimiento m) {
            return base.Channel.add_TipoMovimientoAsync(m);
        }
    }
}
