//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BARBARES_SistemaWeb.ServiceReferenceRol {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rol", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Rol : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Accion {
            get {
                return this.AccionField;
            }
            set {
                if ((object.ReferenceEquals(this.AccionField, value) != true)) {
                    this.AccionField = value;
                    this.RaisePropertyChanged("Accion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRol {
            get {
                return this.IdRolField;
            }
            set {
                if ((this.IdRolField.Equals(value) != true)) {
                    this.IdRolField = value;
                    this.RaisePropertyChanged("IdRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBD", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ResponseBD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlujoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flujo {
            get {
                return this.FlujoField;
            }
            set {
                if ((object.ReferenceEquals(this.FlujoField, value) != true)) {
                    this.FlujoField = value;
                    this.RaisePropertyChanged("Flujo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolXPerfil", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class RolXPerfil : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaAsignacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRolXPerfilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaAsignacion {
            get {
                return this.FechaAsignacionField;
            }
            set {
                if ((this.FechaAsignacionField.Equals(value) != true)) {
                    this.FechaAsignacionField = value;
                    this.RaisePropertyChanged("FechaAsignacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPerfil {
            get {
                return this.IdPerfilField;
            }
            set {
                if ((this.IdPerfilField.Equals(value) != true)) {
                    this.IdPerfilField = value;
                    this.RaisePropertyChanged("IdPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRol {
            get {
                return this.IdRolField;
            }
            set {
                if ((this.IdRolField.Equals(value) != true)) {
                    this.IdRolField = value;
                    this.RaisePropertyChanged("IdRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRolXPerfil {
            get {
                return this.IdRolXPerfilField;
            }
            set {
                if ((this.IdRolXPerfilField.Equals(value) != true)) {
                    this.IdRolXPerfilField = value;
                    this.RaisePropertyChanged("IdRolXPerfil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceRol.IRol_Services")]
    public interface IRol_Services {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol_Services/selectAll_Rol", ReplyAction="http://tempuri.org/IRol_Services/selectAll_RolResponse")]
        BARBARES_SistemaWeb.ServiceReferenceRol.Rol[] selectAll_Rol();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol_Services/selectAll_Rol", ReplyAction="http://tempuri.org/IRol_Services/selectAll_RolResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceRol.Rol[]> selectAll_RolAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol_Services/add_Rol", ReplyAction="http://tempuri.org/IRol_Services/add_RolResponse")]
        BARBARES_SistemaWeb.ServiceReferenceRol.ResponseBD add_Rol(BARBARES_SistemaWeb.ServiceReferenceRol.Rol d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol_Services/add_Rol", ReplyAction="http://tempuri.org/IRol_Services/add_RolResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceRol.ResponseBD> add_RolAsync(BARBARES_SistemaWeb.ServiceReferenceRol.Rol d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol_Services/selectAll_RolXPerfil", ReplyAction="http://tempuri.org/IRol_Services/selectAll_RolXPerfilResponse")]
        BARBARES_SistemaWeb.ServiceReferenceRol.RolXPerfil[] selectAll_RolXPerfil();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol_Services/selectAll_RolXPerfil", ReplyAction="http://tempuri.org/IRol_Services/selectAll_RolXPerfilResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceRol.RolXPerfil[]> selectAll_RolXPerfilAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol_Services/add_RolXPerfil", ReplyAction="http://tempuri.org/IRol_Services/add_RolXPerfilResponse")]
        BARBARES_SistemaWeb.ServiceReferenceRol.ResponseBD add_RolXPerfil(BARBARES_SistemaWeb.ServiceReferenceRol.RolXPerfil d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol_Services/add_RolXPerfil", ReplyAction="http://tempuri.org/IRol_Services/add_RolXPerfilResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceRol.ResponseBD> add_RolXPerfilAsync(BARBARES_SistemaWeb.ServiceReferenceRol.RolXPerfil d);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRol_ServicesChannel : BARBARES_SistemaWeb.ServiceReferenceRol.IRol_Services, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Rol_ServicesClient : System.ServiceModel.ClientBase<BARBARES_SistemaWeb.ServiceReferenceRol.IRol_Services>, BARBARES_SistemaWeb.ServiceReferenceRol.IRol_Services {
        
        public Rol_ServicesClient() {
        }
        
        public Rol_ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Rol_ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Rol_ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Rol_ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceRol.Rol[] selectAll_Rol() {
            return base.Channel.selectAll_Rol();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceRol.Rol[]> selectAll_RolAsync() {
            return base.Channel.selectAll_RolAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceRol.ResponseBD add_Rol(BARBARES_SistemaWeb.ServiceReferenceRol.Rol d) {
            return base.Channel.add_Rol(d);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceRol.ResponseBD> add_RolAsync(BARBARES_SistemaWeb.ServiceReferenceRol.Rol d) {
            return base.Channel.add_RolAsync(d);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceRol.RolXPerfil[] selectAll_RolXPerfil() {
            return base.Channel.selectAll_RolXPerfil();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceRol.RolXPerfil[]> selectAll_RolXPerfilAsync() {
            return base.Channel.selectAll_RolXPerfilAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceRol.ResponseBD add_RolXPerfil(BARBARES_SistemaWeb.ServiceReferenceRol.RolXPerfil d) {
            return base.Channel.add_RolXPerfil(d);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceRol.ResponseBD> add_RolXPerfilAsync(BARBARES_SistemaWeb.ServiceReferenceRol.RolXPerfil d) {
            return base.Channel.add_RolXPerfilAsync(d);
        }
    }
}
