//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BARBARES_SistemaWeb.ServiceReferencePromocion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Promocion", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Promocion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPromocionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SemanaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPromocion {
            get {
                return this.IdPromocionField;
            }
            set {
                if ((this.IdPromocionField.Equals(value) != true)) {
                    this.IdPromocionField = value;
                    this.RaisePropertyChanged("IdPromocion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioUnitario {
            get {
                return this.PrecioUnitarioField;
            }
            set {
                if ((this.PrecioUnitarioField.Equals(value) != true)) {
                    this.PrecioUnitarioField = value;
                    this.RaisePropertyChanged("PrecioUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Semana {
            get {
                return this.SemanaField;
            }
            set {
                if ((this.SemanaField.Equals(value) != true)) {
                    this.SemanaField = value;
                    this.RaisePropertyChanged("Semana");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBD", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ResponseBD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlujoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flujo {
            get {
                return this.FlujoField;
            }
            set {
                if ((object.ReferenceEquals(this.FlujoField, value) != true)) {
                    this.FlujoField = value;
                    this.RaisePropertyChanged("Flujo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetallePromocion", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class DetallePromocion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDetallePromocionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPromocionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioUnitarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDetallePromocion {
            get {
                return this.IdDetallePromocionField;
            }
            set {
                if ((this.IdDetallePromocionField.Equals(value) != true)) {
                    this.IdDetallePromocionField = value;
                    this.RaisePropertyChanged("IdDetallePromocion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPromocion {
            get {
                return this.IdPromocionField;
            }
            set {
                if ((this.IdPromocionField.Equals(value) != true)) {
                    this.IdPromocionField = value;
                    this.RaisePropertyChanged("IdPromocion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioUnitario {
            get {
                return this.PrecioUnitarioField;
            }
            set {
                if ((this.PrecioUnitarioField.Equals(value) != true)) {
                    this.PrecioUnitarioField = value;
                    this.RaisePropertyChanged("PrecioUnitario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePromocion.IPromocion_Services")]
    public interface IPromocion_Services {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromocion_Services/selectAll_Promocion", ReplyAction="http://tempuri.org/IPromocion_Services/selectAll_PromocionResponse")]
        BARBARES_SistemaWeb.ServiceReferencePromocion.Promocion[] selectAll_Promocion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromocion_Services/selectAll_Promocion", ReplyAction="http://tempuri.org/IPromocion_Services/selectAll_PromocionResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePromocion.Promocion[]> selectAll_PromocionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromocion_Services/add_Promocion", ReplyAction="http://tempuri.org/IPromocion_Services/add_PromocionResponse")]
        BARBARES_SistemaWeb.ServiceReferencePromocion.ResponseBD add_Promocion(BARBARES_SistemaWeb.ServiceReferencePromocion.Promocion p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromocion_Services/add_Promocion", ReplyAction="http://tempuri.org/IPromocion_Services/add_PromocionResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePromocion.ResponseBD> add_PromocionAsync(BARBARES_SistemaWeb.ServiceReferencePromocion.Promocion p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromocion_Services/selectAll_DetallePromocion", ReplyAction="http://tempuri.org/IPromocion_Services/selectAll_DetallePromocionResponse")]
        BARBARES_SistemaWeb.ServiceReferencePromocion.DetallePromocion[] selectAll_DetallePromocion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromocion_Services/selectAll_DetallePromocion", ReplyAction="http://tempuri.org/IPromocion_Services/selectAll_DetallePromocionResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePromocion.DetallePromocion[]> selectAll_DetallePromocionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromocion_Services/add_DetallePromocion", ReplyAction="http://tempuri.org/IPromocion_Services/add_DetallePromocionResponse")]
        BARBARES_SistemaWeb.ServiceReferencePromocion.ResponseBD add_DetallePromocion(BARBARES_SistemaWeb.ServiceReferencePromocion.DetallePromocion d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromocion_Services/add_DetallePromocion", ReplyAction="http://tempuri.org/IPromocion_Services/add_DetallePromocionResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePromocion.ResponseBD> add_DetallePromocionAsync(BARBARES_SistemaWeb.ServiceReferencePromocion.DetallePromocion d);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPromocion_ServicesChannel : BARBARES_SistemaWeb.ServiceReferencePromocion.IPromocion_Services, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Promocion_ServicesClient : System.ServiceModel.ClientBase<BARBARES_SistemaWeb.ServiceReferencePromocion.IPromocion_Services>, BARBARES_SistemaWeb.ServiceReferencePromocion.IPromocion_Services {
        
        public Promocion_ServicesClient() {
        }
        
        public Promocion_ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Promocion_ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Promocion_ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Promocion_ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePromocion.Promocion[] selectAll_Promocion() {
            return base.Channel.selectAll_Promocion();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePromocion.Promocion[]> selectAll_PromocionAsync() {
            return base.Channel.selectAll_PromocionAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePromocion.ResponseBD add_Promocion(BARBARES_SistemaWeb.ServiceReferencePromocion.Promocion p) {
            return base.Channel.add_Promocion(p);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePromocion.ResponseBD> add_PromocionAsync(BARBARES_SistemaWeb.ServiceReferencePromocion.Promocion p) {
            return base.Channel.add_PromocionAsync(p);
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePromocion.DetallePromocion[] selectAll_DetallePromocion() {
            return base.Channel.selectAll_DetallePromocion();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePromocion.DetallePromocion[]> selectAll_DetallePromocionAsync() {
            return base.Channel.selectAll_DetallePromocionAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePromocion.ResponseBD add_DetallePromocion(BARBARES_SistemaWeb.ServiceReferencePromocion.DetallePromocion d) {
            return base.Channel.add_DetallePromocion(d);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePromocion.ResponseBD> add_DetallePromocionAsync(BARBARES_SistemaWeb.ServiceReferencePromocion.DetallePromocion d) {
            return base.Channel.add_DetallePromocionAsync(d);
        }
    }
}
