//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BARBARES_SistemaWeb.ServiceReferenceMoneda {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Moneda", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Moneda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SimboloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMoneda {
            get {
                return this.IdMonedaField;
            }
            set {
                if ((this.IdMonedaField.Equals(value) != true)) {
                    this.IdMonedaField = value;
                    this.RaisePropertyChanged("IdMoneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Simbolo {
            get {
                return this.SimboloField;
            }
            set {
                if ((object.ReferenceEquals(this.SimboloField, value) != true)) {
                    this.SimboloField = value;
                    this.RaisePropertyChanged("Simbolo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBD", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ResponseBD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlujoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flujo {
            get {
                return this.FlujoField;
            }
            set {
                if ((object.ReferenceEquals(this.FlujoField, value) != true)) {
                    this.FlujoField = value;
                    this.RaisePropertyChanged("Flujo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceMoneda.IMoneda_Services")]
    public interface IMoneda_Services {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoneda_Services/selectAll_Moneda", ReplyAction="http://tempuri.org/IMoneda_Services/selectAll_MonedaResponse")]
        BARBARES_SistemaWeb.ServiceReferenceMoneda.Moneda[] selectAll_Moneda();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoneda_Services/selectAll_Moneda", ReplyAction="http://tempuri.org/IMoneda_Services/selectAll_MonedaResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceMoneda.Moneda[]> selectAll_MonedaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoneda_Services/add_Moneda", ReplyAction="http://tempuri.org/IMoneda_Services/add_MonedaResponse")]
        BARBARES_SistemaWeb.ServiceReferenceMoneda.ResponseBD add_Moneda(BARBARES_SistemaWeb.ServiceReferenceMoneda.Moneda m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoneda_Services/add_Moneda", ReplyAction="http://tempuri.org/IMoneda_Services/add_MonedaResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceMoneda.ResponseBD> add_MonedaAsync(BARBARES_SistemaWeb.ServiceReferenceMoneda.Moneda m);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMoneda_ServicesChannel : BARBARES_SistemaWeb.ServiceReferenceMoneda.IMoneda_Services, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Moneda_ServicesClient : System.ServiceModel.ClientBase<BARBARES_SistemaWeb.ServiceReferenceMoneda.IMoneda_Services>, BARBARES_SistemaWeb.ServiceReferenceMoneda.IMoneda_Services {
        
        public Moneda_ServicesClient() {
        }
        
        public Moneda_ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Moneda_ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Moneda_ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Moneda_ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceMoneda.Moneda[] selectAll_Moneda() {
            return base.Channel.selectAll_Moneda();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceMoneda.Moneda[]> selectAll_MonedaAsync() {
            return base.Channel.selectAll_MonedaAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceMoneda.ResponseBD add_Moneda(BARBARES_SistemaWeb.ServiceReferenceMoneda.Moneda m) {
            return base.Channel.add_Moneda(m);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceMoneda.ResponseBD> add_MonedaAsync(BARBARES_SistemaWeb.ServiceReferenceMoneda.Moneda m) {
            return base.Channel.add_MonedaAsync(m);
        }
    }
}
