//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BARBARES_SistemaWeb.ServiceReferenceComprobante {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComprobantePago", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ComprobantePago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdComprobantePagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransaccionPOSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdComprobantePago {
            get {
                return this.IdComprobantePagoField;
            }
            set {
                if ((this.IdComprobantePagoField.Equals(value) != true)) {
                    this.IdComprobantePagoField = value;
                    this.RaisePropertyChanged("IdComprobantePago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMoneda {
            get {
                return this.IdMonedaField;
            }
            set {
                if ((this.IdMonedaField.Equals(value) != true)) {
                    this.IdMonedaField = value;
                    this.RaisePropertyChanged("IdMoneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPedido {
            get {
                return this.IdPedidoField;
            }
            set {
                if ((this.IdPedidoField.Equals(value) != true)) {
                    this.IdPedidoField = value;
                    this.RaisePropertyChanged("IdPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPersona {
            get {
                return this.IdPersonaField;
            }
            set {
                if ((this.IdPersonaField.Equals(value) != true)) {
                    this.IdPersonaField = value;
                    this.RaisePropertyChanged("IdPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoComprobante {
            get {
                return this.IdTipoComprobanteField;
            }
            set {
                if ((this.IdTipoComprobanteField.Equals(value) != true)) {
                    this.IdTipoComprobanteField = value;
                    this.RaisePropertyChanged("IdTipoComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroComprobante {
            get {
                return this.NumeroComprobanteField;
            }
            set {
                if ((this.NumeroComprobanteField.Equals(value) != true)) {
                    this.NumeroComprobanteField = value;
                    this.RaisePropertyChanged("NumeroComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransaccionPOS {
            get {
                return this.TransaccionPOSField;
            }
            set {
                if ((this.TransaccionPOSField.Equals(value) != true)) {
                    this.TransaccionPOSField = value;
                    this.RaisePropertyChanged("TransaccionPOS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBD", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ResponseBD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlujoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flujo {
            get {
                return this.FlujoField;
            }
            set {
                if ((object.ReferenceEquals(this.FlujoField, value) != true)) {
                    this.FlujoField = value;
                    this.RaisePropertyChanged("Flujo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleComprobante", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class DetalleComprobante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdComprobantePagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDetalleComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPromocionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SubtotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdComprobantePago {
            get {
                return this.IdComprobantePagoField;
            }
            set {
                if ((this.IdComprobantePagoField.Equals(value) != true)) {
                    this.IdComprobantePagoField = value;
                    this.RaisePropertyChanged("IdComprobantePago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDetalleComprobante {
            get {
                return this.IdDetalleComprobanteField;
            }
            set {
                if ((this.IdDetalleComprobanteField.Equals(value) != true)) {
                    this.IdDetalleComprobanteField = value;
                    this.RaisePropertyChanged("IdDetalleComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPromocion {
            get {
                return this.IdPromocionField;
            }
            set {
                if ((this.IdPromocionField.Equals(value) != true)) {
                    this.IdPromocionField = value;
                    this.RaisePropertyChanged("IdPromocion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Subtotal {
            get {
                return this.SubtotalField;
            }
            set {
                if ((this.SubtotalField.Equals(value) != true)) {
                    this.SubtotalField = value;
                    this.RaisePropertyChanged("Subtotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedioPago", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class MedioPago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMedioPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMedioPago {
            get {
                return this.IdMedioPagoField;
            }
            set {
                if ((this.IdMedioPagoField.Equals(value) != true)) {
                    this.IdMedioPagoField = value;
                    this.RaisePropertyChanged("IdMedioPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoTarjeta {
            get {
                return this.IdTipoTarjetaField;
            }
            set {
                if ((this.IdTipoTarjetaField.Equals(value) != true)) {
                    this.IdTipoTarjetaField = value;
                    this.RaisePropertyChanged("IdTipoTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoComprobante", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class TipoComprobante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoComprobante {
            get {
                return this.IdTipoComprobanteField;
            }
            set {
                if ((this.IdTipoComprobanteField.Equals(value) != true)) {
                    this.IdTipoComprobanteField = value;
                    this.RaisePropertyChanged("IdTipoComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoTarjeta", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class TipoTarjeta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoTarjeta {
            get {
                return this.IdTipoTarjetaField;
            }
            set {
                if ((this.IdTipoTarjetaField.Equals(value) != true)) {
                    this.IdTipoTarjetaField = value;
                    this.RaisePropertyChanged("IdTipoTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceComprobante.IComprobante_Services")]
    public interface IComprobante_Services {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/selectAll_Comprobante", ReplyAction="http://tempuri.org/IComprobante_Services/selectAll_ComprobanteResponse")]
        BARBARES_SistemaWeb.ServiceReferenceComprobante.ComprobantePago[] selectAll_Comprobante();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/selectAll_Comprobante", ReplyAction="http://tempuri.org/IComprobante_Services/selectAll_ComprobanteResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.ComprobantePago[]> selectAll_ComprobanteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/add_Comprobante", ReplyAction="http://tempuri.org/IComprobante_Services/add_ComprobanteResponse")]
        BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD add_Comprobante(BARBARES_SistemaWeb.ServiceReferenceComprobante.ComprobantePago c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/add_Comprobante", ReplyAction="http://tempuri.org/IComprobante_Services/add_ComprobanteResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD> add_ComprobanteAsync(BARBARES_SistemaWeb.ServiceReferenceComprobante.ComprobantePago c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/selectAll_DetalleComprobante", ReplyAction="http://tempuri.org/IComprobante_Services/selectAll_DetalleComprobanteResponse")]
        BARBARES_SistemaWeb.ServiceReferenceComprobante.DetalleComprobante[] selectAll_DetalleComprobante();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/selectAll_DetalleComprobante", ReplyAction="http://tempuri.org/IComprobante_Services/selectAll_DetalleComprobanteResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.DetalleComprobante[]> selectAll_DetalleComprobanteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/add_DetalleComprobante", ReplyAction="http://tempuri.org/IComprobante_Services/add_DetalleComprobanteResponse")]
        BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD add_DetalleComprobante(BARBARES_SistemaWeb.ServiceReferenceComprobante.DetalleComprobante d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/add_DetalleComprobante", ReplyAction="http://tempuri.org/IComprobante_Services/add_DetalleComprobanteResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD> add_DetalleComprobanteAsync(BARBARES_SistemaWeb.ServiceReferenceComprobante.DetalleComprobante d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/selectAll_MedioPago", ReplyAction="http://tempuri.org/IComprobante_Services/selectAll_MedioPagoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceComprobante.MedioPago[] selectAll_MedioPago();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/selectAll_MedioPago", ReplyAction="http://tempuri.org/IComprobante_Services/selectAll_MedioPagoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.MedioPago[]> selectAll_MedioPagoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/add_MedioPago", ReplyAction="http://tempuri.org/IComprobante_Services/add_MedioPagoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD add_MedioPago(BARBARES_SistemaWeb.ServiceReferenceComprobante.MedioPago m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/add_MedioPago", ReplyAction="http://tempuri.org/IComprobante_Services/add_MedioPagoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD> add_MedioPagoAsync(BARBARES_SistemaWeb.ServiceReferenceComprobante.MedioPago m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/selectAll_TipoComprobante", ReplyAction="http://tempuri.org/IComprobante_Services/selectAll_TipoComprobanteResponse")]
        BARBARES_SistemaWeb.ServiceReferenceComprobante.TipoComprobante[] selectAll_TipoComprobante();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/selectAll_TipoComprobante", ReplyAction="http://tempuri.org/IComprobante_Services/selectAll_TipoComprobanteResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.TipoComprobante[]> selectAll_TipoComprobanteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/add_TipoComprobante", ReplyAction="http://tempuri.org/IComprobante_Services/add_TipoComprobanteResponse")]
        BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD add_TipoComprobante(BARBARES_SistemaWeb.ServiceReferenceComprobante.TipoComprobante t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/add_TipoComprobante", ReplyAction="http://tempuri.org/IComprobante_Services/add_TipoComprobanteResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD> add_TipoComprobanteAsync(BARBARES_SistemaWeb.ServiceReferenceComprobante.TipoComprobante t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/selectAll_TipoTarjeta", ReplyAction="http://tempuri.org/IComprobante_Services/selectAll_TipoTarjetaResponse")]
        BARBARES_SistemaWeb.ServiceReferenceComprobante.TipoTarjeta[] selectAll_TipoTarjeta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/selectAll_TipoTarjeta", ReplyAction="http://tempuri.org/IComprobante_Services/selectAll_TipoTarjetaResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.TipoTarjeta[]> selectAll_TipoTarjetaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/add_TipoTarjeta", ReplyAction="http://tempuri.org/IComprobante_Services/add_TipoTarjetaResponse")]
        BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD add_TipoTarjeta(BARBARES_SistemaWeb.ServiceReferenceComprobante.TipoTarjeta t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobante_Services/add_TipoTarjeta", ReplyAction="http://tempuri.org/IComprobante_Services/add_TipoTarjetaResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD> add_TipoTarjetaAsync(BARBARES_SistemaWeb.ServiceReferenceComprobante.TipoTarjeta t);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComprobante_ServicesChannel : BARBARES_SistemaWeb.ServiceReferenceComprobante.IComprobante_Services, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Comprobante_ServicesClient : System.ServiceModel.ClientBase<BARBARES_SistemaWeb.ServiceReferenceComprobante.IComprobante_Services>, BARBARES_SistemaWeb.ServiceReferenceComprobante.IComprobante_Services {
        
        public Comprobante_ServicesClient() {
        }
        
        public Comprobante_ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Comprobante_ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Comprobante_ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Comprobante_ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceComprobante.ComprobantePago[] selectAll_Comprobante() {
            return base.Channel.selectAll_Comprobante();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.ComprobantePago[]> selectAll_ComprobanteAsync() {
            return base.Channel.selectAll_ComprobanteAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD add_Comprobante(BARBARES_SistemaWeb.ServiceReferenceComprobante.ComprobantePago c) {
            return base.Channel.add_Comprobante(c);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD> add_ComprobanteAsync(BARBARES_SistemaWeb.ServiceReferenceComprobante.ComprobantePago c) {
            return base.Channel.add_ComprobanteAsync(c);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceComprobante.DetalleComprobante[] selectAll_DetalleComprobante() {
            return base.Channel.selectAll_DetalleComprobante();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.DetalleComprobante[]> selectAll_DetalleComprobanteAsync() {
            return base.Channel.selectAll_DetalleComprobanteAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD add_DetalleComprobante(BARBARES_SistemaWeb.ServiceReferenceComprobante.DetalleComprobante d) {
            return base.Channel.add_DetalleComprobante(d);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD> add_DetalleComprobanteAsync(BARBARES_SistemaWeb.ServiceReferenceComprobante.DetalleComprobante d) {
            return base.Channel.add_DetalleComprobanteAsync(d);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceComprobante.MedioPago[] selectAll_MedioPago() {
            return base.Channel.selectAll_MedioPago();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.MedioPago[]> selectAll_MedioPagoAsync() {
            return base.Channel.selectAll_MedioPagoAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD add_MedioPago(BARBARES_SistemaWeb.ServiceReferenceComprobante.MedioPago m) {
            return base.Channel.add_MedioPago(m);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD> add_MedioPagoAsync(BARBARES_SistemaWeb.ServiceReferenceComprobante.MedioPago m) {
            return base.Channel.add_MedioPagoAsync(m);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceComprobante.TipoComprobante[] selectAll_TipoComprobante() {
            return base.Channel.selectAll_TipoComprobante();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.TipoComprobante[]> selectAll_TipoComprobanteAsync() {
            return base.Channel.selectAll_TipoComprobanteAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD add_TipoComprobante(BARBARES_SistemaWeb.ServiceReferenceComprobante.TipoComprobante t) {
            return base.Channel.add_TipoComprobante(t);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD> add_TipoComprobanteAsync(BARBARES_SistemaWeb.ServiceReferenceComprobante.TipoComprobante t) {
            return base.Channel.add_TipoComprobanteAsync(t);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceComprobante.TipoTarjeta[] selectAll_TipoTarjeta() {
            return base.Channel.selectAll_TipoTarjeta();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.TipoTarjeta[]> selectAll_TipoTarjetaAsync() {
            return base.Channel.selectAll_TipoTarjetaAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD add_TipoTarjeta(BARBARES_SistemaWeb.ServiceReferenceComprobante.TipoTarjeta t) {
            return base.Channel.add_TipoTarjeta(t);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceComprobante.ResponseBD> add_TipoTarjetaAsync(BARBARES_SistemaWeb.ServiceReferenceComprobante.TipoTarjeta t) {
            return base.Channel.add_TipoTarjetaAsync(t);
        }
    }
}
