//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BARBARES_SistemaWeb.ServiceReferenceDireccion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Direccion", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Direccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoCalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoUrbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MzltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrbanizacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calle {
            get {
                return this.CalleField;
            }
            set {
                if ((object.ReferenceEquals(this.CalleField, value) != true)) {
                    this.CalleField = value;
                    this.RaisePropertyChanged("Calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDepartamento {
            get {
                return this.IdDepartamentoField;
            }
            set {
                if ((this.IdDepartamentoField.Equals(value) != true)) {
                    this.IdDepartamentoField = value;
                    this.RaisePropertyChanged("IdDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDireccion {
            get {
                return this.IdDireccionField;
            }
            set {
                if ((this.IdDireccionField.Equals(value) != true)) {
                    this.IdDireccionField = value;
                    this.RaisePropertyChanged("IdDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDistrito {
            get {
                return this.IdDistritoField;
            }
            set {
                if ((this.IdDistritoField.Equals(value) != true)) {
                    this.IdDistritoField = value;
                    this.RaisePropertyChanged("IdDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProvincia {
            get {
                return this.IdProvinciaField;
            }
            set {
                if ((this.IdProvinciaField.Equals(value) != true)) {
                    this.IdProvinciaField = value;
                    this.RaisePropertyChanged("IdProvincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoCalle {
            get {
                return this.IdTipoCalleField;
            }
            set {
                if ((this.IdTipoCalleField.Equals(value) != true)) {
                    this.IdTipoCalleField = value;
                    this.RaisePropertyChanged("IdTipoCalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoUrb {
            get {
                return this.IdTipoUrbField;
            }
            set {
                if ((this.IdTipoUrbField.Equals(value) != true)) {
                    this.IdTipoUrbField = value;
                    this.RaisePropertyChanged("IdTipoUrb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Interior {
            get {
                return this.InteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.InteriorField, value) != true)) {
                    this.InteriorField = value;
                    this.RaisePropertyChanged("Interior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mzlt {
            get {
                return this.MzltField;
            }
            set {
                if ((object.ReferenceEquals(this.MzltField, value) != true)) {
                    this.MzltField = value;
                    this.RaisePropertyChanged("Mzlt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia {
            get {
                return this.ReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciaField, value) != true)) {
                    this.ReferenciaField = value;
                    this.RaisePropertyChanged("Referencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Urbanizacion {
            get {
                return this.UrbanizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UrbanizacionField, value) != true)) {
                    this.UrbanizacionField = value;
                    this.RaisePropertyChanged("Urbanizacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBD", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ResponseBD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlujoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flujo {
            get {
                return this.FlujoField;
            }
            set {
                if ((object.ReferenceEquals(this.FlujoField, value) != true)) {
                    this.FlujoField = value;
                    this.RaisePropertyChanged("Flujo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Departamento", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Departamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDepartamento {
            get {
                return this.IdDepartamentoField;
            }
            set {
                if ((this.IdDepartamentoField.Equals(value) != true)) {
                    this.IdDepartamentoField = value;
                    this.RaisePropertyChanged("IdDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Provincia", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Provincia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDepartamento {
            get {
                return this.IdDepartamentoField;
            }
            set {
                if ((this.IdDepartamentoField.Equals(value) != true)) {
                    this.IdDepartamentoField = value;
                    this.RaisePropertyChanged("IdDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProvincia {
            get {
                return this.IdProvinciaField;
            }
            set {
                if ((this.IdProvinciaField.Equals(value) != true)) {
                    this.IdProvinciaField = value;
                    this.RaisePropertyChanged("IdProvincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Distrito", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Distrito : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDepartamento {
            get {
                return this.IdDepartamentoField;
            }
            set {
                if ((this.IdDepartamentoField.Equals(value) != true)) {
                    this.IdDepartamentoField = value;
                    this.RaisePropertyChanged("IdDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDistrito {
            get {
                return this.IdDistritoField;
            }
            set {
                if ((this.IdDistritoField.Equals(value) != true)) {
                    this.IdDistritoField = value;
                    this.RaisePropertyChanged("IdDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProvincia {
            get {
                return this.IdProvinciaField;
            }
            set {
                if ((this.IdProvinciaField.Equals(value) != true)) {
                    this.IdProvinciaField = value;
                    this.RaisePropertyChanged("IdProvincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoCalle", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class TipoCalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoCalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoCalle {
            get {
                return this.IdTipoCalleField;
            }
            set {
                if ((this.IdTipoCalleField.Equals(value) != true)) {
                    this.IdTipoCalleField = value;
                    this.RaisePropertyChanged("IdTipoCalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoUrb", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class TipoUrb : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoUrbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoUrb {
            get {
                return this.IdTipoUrbField;
            }
            set {
                if ((this.IdTipoUrbField.Equals(value) != true)) {
                    this.IdTipoUrbField = value;
                    this.RaisePropertyChanged("IdTipoUrb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDireccion.IDireccion_Services")]
    public interface IDireccion_Services {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/selectAll_Direccion", ReplyAction="http://tempuri.org/IDireccion_Services/selectAll_DireccionResponse")]
        BARBARES_SistemaWeb.ServiceReferenceDireccion.Direccion[] selectAll_Direccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/selectAll_Direccion", ReplyAction="http://tempuri.org/IDireccion_Services/selectAll_DireccionResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.Direccion[]> selectAll_DireccionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/add_Direccion", ReplyAction="http://tempuri.org/IDireccion_Services/add_DireccionResponse")]
        BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD add_Direccion(BARBARES_SistemaWeb.ServiceReferenceDireccion.Direccion t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/add_Direccion", ReplyAction="http://tempuri.org/IDireccion_Services/add_DireccionResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD> add_DireccionAsync(BARBARES_SistemaWeb.ServiceReferenceDireccion.Direccion t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/selectAll_Departamento", ReplyAction="http://tempuri.org/IDireccion_Services/selectAll_DepartamentoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceDireccion.Departamento[] selectAll_Departamento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/selectAll_Departamento", ReplyAction="http://tempuri.org/IDireccion_Services/selectAll_DepartamentoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.Departamento[]> selectAll_DepartamentoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/add_Departamento", ReplyAction="http://tempuri.org/IDireccion_Services/add_DepartamentoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD add_Departamento(BARBARES_SistemaWeb.ServiceReferenceDireccion.Departamento t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/add_Departamento", ReplyAction="http://tempuri.org/IDireccion_Services/add_DepartamentoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD> add_DepartamentoAsync(BARBARES_SistemaWeb.ServiceReferenceDireccion.Departamento t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/selectAll_Provincia", ReplyAction="http://tempuri.org/IDireccion_Services/selectAll_ProvinciaResponse")]
        BARBARES_SistemaWeb.ServiceReferenceDireccion.Provincia[] selectAll_Provincia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/selectAll_Provincia", ReplyAction="http://tempuri.org/IDireccion_Services/selectAll_ProvinciaResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.Provincia[]> selectAll_ProvinciaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/add_Provincia", ReplyAction="http://tempuri.org/IDireccion_Services/add_ProvinciaResponse")]
        BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD add_Provincia(BARBARES_SistemaWeb.ServiceReferenceDireccion.Provincia t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/add_Provincia", ReplyAction="http://tempuri.org/IDireccion_Services/add_ProvinciaResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD> add_ProvinciaAsync(BARBARES_SistemaWeb.ServiceReferenceDireccion.Provincia t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/selectAll_Distrito", ReplyAction="http://tempuri.org/IDireccion_Services/selectAll_DistritoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceDireccion.Distrito[] selectAll_Distrito();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/selectAll_Distrito", ReplyAction="http://tempuri.org/IDireccion_Services/selectAll_DistritoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.Distrito[]> selectAll_DistritoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/add_Distrito", ReplyAction="http://tempuri.org/IDireccion_Services/add_DistritoResponse")]
        BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD add_Distrito(BARBARES_SistemaWeb.ServiceReferenceDireccion.Distrito t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/add_Distrito", ReplyAction="http://tempuri.org/IDireccion_Services/add_DistritoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD> add_DistritoAsync(BARBARES_SistemaWeb.ServiceReferenceDireccion.Distrito t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/selectAll_TipoCalle", ReplyAction="http://tempuri.org/IDireccion_Services/selectAll_TipoCalleResponse")]
        BARBARES_SistemaWeb.ServiceReferenceDireccion.TipoCalle[] selectAll_TipoCalle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/selectAll_TipoCalle", ReplyAction="http://tempuri.org/IDireccion_Services/selectAll_TipoCalleResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.TipoCalle[]> selectAll_TipoCalleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/add_TipoCalle", ReplyAction="http://tempuri.org/IDireccion_Services/add_TipoCalleResponse")]
        BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD add_TipoCalle(BARBARES_SistemaWeb.ServiceReferenceDireccion.TipoCalle t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/add_TipoCalle", ReplyAction="http://tempuri.org/IDireccion_Services/add_TipoCalleResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD> add_TipoCalleAsync(BARBARES_SistemaWeb.ServiceReferenceDireccion.TipoCalle t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/selectAll_TipoUrb", ReplyAction="http://tempuri.org/IDireccion_Services/selectAll_TipoUrbResponse")]
        BARBARES_SistemaWeb.ServiceReferenceDireccion.TipoUrb[] selectAll_TipoUrb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/selectAll_TipoUrb", ReplyAction="http://tempuri.org/IDireccion_Services/selectAll_TipoUrbResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.TipoUrb[]> selectAll_TipoUrbAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/add_TipoUrb", ReplyAction="http://tempuri.org/IDireccion_Services/add_TipoUrbResponse")]
        BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD add_TipoUrb(BARBARES_SistemaWeb.ServiceReferenceDireccion.TipoUrb t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccion_Services/add_TipoUrb", ReplyAction="http://tempuri.org/IDireccion_Services/add_TipoUrbResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD> add_TipoUrbAsync(BARBARES_SistemaWeb.ServiceReferenceDireccion.TipoUrb t);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDireccion_ServicesChannel : BARBARES_SistemaWeb.ServiceReferenceDireccion.IDireccion_Services, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Direccion_ServicesClient : System.ServiceModel.ClientBase<BARBARES_SistemaWeb.ServiceReferenceDireccion.IDireccion_Services>, BARBARES_SistemaWeb.ServiceReferenceDireccion.IDireccion_Services {
        
        public Direccion_ServicesClient() {
        }
        
        public Direccion_ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Direccion_ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Direccion_ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Direccion_ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceDireccion.Direccion[] selectAll_Direccion() {
            return base.Channel.selectAll_Direccion();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.Direccion[]> selectAll_DireccionAsync() {
            return base.Channel.selectAll_DireccionAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD add_Direccion(BARBARES_SistemaWeb.ServiceReferenceDireccion.Direccion t) {
            return base.Channel.add_Direccion(t);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD> add_DireccionAsync(BARBARES_SistemaWeb.ServiceReferenceDireccion.Direccion t) {
            return base.Channel.add_DireccionAsync(t);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceDireccion.Departamento[] selectAll_Departamento() {
            return base.Channel.selectAll_Departamento();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.Departamento[]> selectAll_DepartamentoAsync() {
            return base.Channel.selectAll_DepartamentoAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD add_Departamento(BARBARES_SistemaWeb.ServiceReferenceDireccion.Departamento t) {
            return base.Channel.add_Departamento(t);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD> add_DepartamentoAsync(BARBARES_SistemaWeb.ServiceReferenceDireccion.Departamento t) {
            return base.Channel.add_DepartamentoAsync(t);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceDireccion.Provincia[] selectAll_Provincia() {
            return base.Channel.selectAll_Provincia();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.Provincia[]> selectAll_ProvinciaAsync() {
            return base.Channel.selectAll_ProvinciaAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD add_Provincia(BARBARES_SistemaWeb.ServiceReferenceDireccion.Provincia t) {
            return base.Channel.add_Provincia(t);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD> add_ProvinciaAsync(BARBARES_SistemaWeb.ServiceReferenceDireccion.Provincia t) {
            return base.Channel.add_ProvinciaAsync(t);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceDireccion.Distrito[] selectAll_Distrito() {
            return base.Channel.selectAll_Distrito();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.Distrito[]> selectAll_DistritoAsync() {
            return base.Channel.selectAll_DistritoAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD add_Distrito(BARBARES_SistemaWeb.ServiceReferenceDireccion.Distrito t) {
            return base.Channel.add_Distrito(t);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD> add_DistritoAsync(BARBARES_SistemaWeb.ServiceReferenceDireccion.Distrito t) {
            return base.Channel.add_DistritoAsync(t);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceDireccion.TipoCalle[] selectAll_TipoCalle() {
            return base.Channel.selectAll_TipoCalle();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.TipoCalle[]> selectAll_TipoCalleAsync() {
            return base.Channel.selectAll_TipoCalleAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD add_TipoCalle(BARBARES_SistemaWeb.ServiceReferenceDireccion.TipoCalle t) {
            return base.Channel.add_TipoCalle(t);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD> add_TipoCalleAsync(BARBARES_SistemaWeb.ServiceReferenceDireccion.TipoCalle t) {
            return base.Channel.add_TipoCalleAsync(t);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceDireccion.TipoUrb[] selectAll_TipoUrb() {
            return base.Channel.selectAll_TipoUrb();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.TipoUrb[]> selectAll_TipoUrbAsync() {
            return base.Channel.selectAll_TipoUrbAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD add_TipoUrb(BARBARES_SistemaWeb.ServiceReferenceDireccion.TipoUrb t) {
            return base.Channel.add_TipoUrb(t);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceDireccion.ResponseBD> add_TipoUrbAsync(BARBARES_SistemaWeb.ServiceReferenceDireccion.TipoUrb t) {
            return base.Channel.add_TipoUrbAsync(t);
        }
    }
}
