//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BARBARES_SistemaWeb.ServiceReferenceUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdContrasena {
            get {
                return this.IdContrasenaField;
            }
            set {
                if ((this.IdContrasenaField.Equals(value) != true)) {
                    this.IdContrasenaField = value;
                    this.RaisePropertyChanged("IdContrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBD", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ResponseBD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlujoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flujo {
            get {
                return this.FlujoField;
            }
            set {
                if ((object.ReferenceEquals(this.FlujoField, value) != true)) {
                    this.FlujoField = value;
                    this.RaisePropertyChanged("Flujo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogUsuario", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class LogUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdLogUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorAnteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorPosteriorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Accion {
            get {
                return this.AccionField;
            }
            set {
                if ((object.ReferenceEquals(this.AccionField, value) != true)) {
                    this.AccionField = value;
                    this.RaisePropertyChanged("Accion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clase {
            get {
                return this.ClaseField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaseField, value) != true)) {
                    this.ClaseField = value;
                    this.RaisePropertyChanged("Clase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLogUsuario {
            get {
                return this.IdLogUsuarioField;
            }
            set {
                if ((this.IdLogUsuarioField.Equals(value) != true)) {
                    this.IdLogUsuarioField = value;
                    this.RaisePropertyChanged("IdLogUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ip {
            get {
                return this.IpField;
            }
            set {
                if ((object.ReferenceEquals(this.IpField, value) != true)) {
                    this.IpField = value;
                    this.RaisePropertyChanged("Ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValorAnterior {
            get {
                return this.ValorAnteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorAnteriorField, value) != true)) {
                    this.ValorAnteriorField = value;
                    this.RaisePropertyChanged("ValorAnterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValorPosterior {
            get {
                return this.ValorPosteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorPosteriorField, value) != true)) {
                    this.ValorPosteriorField = value;
                    this.RaisePropertyChanged("ValorPosterior");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUsuario.IUsuario_Services")]
    public interface IUsuario_Services {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario_Services/selectAll_Usuario", ReplyAction="http://tempuri.org/IUsuario_Services/selectAll_UsuarioResponse")]
        BARBARES_SistemaWeb.ServiceReferenceUsuario.Usuario[] selectAll_Usuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario_Services/selectAll_Usuario", ReplyAction="http://tempuri.org/IUsuario_Services/selectAll_UsuarioResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceUsuario.Usuario[]> selectAll_UsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario_Services/add_Usuario", ReplyAction="http://tempuri.org/IUsuario_Services/add_UsuarioResponse")]
        BARBARES_SistemaWeb.ServiceReferenceUsuario.ResponseBD add_Usuario(BARBARES_SistemaWeb.ServiceReferenceUsuario.Usuario t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario_Services/add_Usuario", ReplyAction="http://tempuri.org/IUsuario_Services/add_UsuarioResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceUsuario.ResponseBD> add_UsuarioAsync(BARBARES_SistemaWeb.ServiceReferenceUsuario.Usuario t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario_Services/selectAll_LogUsuario", ReplyAction="http://tempuri.org/IUsuario_Services/selectAll_LogUsuarioResponse")]
        BARBARES_SistemaWeb.ServiceReferenceUsuario.LogUsuario[] selectAll_LogUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario_Services/selectAll_LogUsuario", ReplyAction="http://tempuri.org/IUsuario_Services/selectAll_LogUsuarioResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceUsuario.LogUsuario[]> selectAll_LogUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario_Services/add_LogUsuario", ReplyAction="http://tempuri.org/IUsuario_Services/add_LogUsuarioResponse")]
        BARBARES_SistemaWeb.ServiceReferenceUsuario.ResponseBD add_LogUsuario(BARBARES_SistemaWeb.ServiceReferenceUsuario.LogUsuario t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario_Services/add_LogUsuario", ReplyAction="http://tempuri.org/IUsuario_Services/add_LogUsuarioResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceUsuario.ResponseBD> add_LogUsuarioAsync(BARBARES_SistemaWeb.ServiceReferenceUsuario.LogUsuario t);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuario_ServicesChannel : BARBARES_SistemaWeb.ServiceReferenceUsuario.IUsuario_Services, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Usuario_ServicesClient : System.ServiceModel.ClientBase<BARBARES_SistemaWeb.ServiceReferenceUsuario.IUsuario_Services>, BARBARES_SistemaWeb.ServiceReferenceUsuario.IUsuario_Services {
        
        public Usuario_ServicesClient() {
        }
        
        public Usuario_ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Usuario_ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Usuario_ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Usuario_ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceUsuario.Usuario[] selectAll_Usuario() {
            return base.Channel.selectAll_Usuario();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceUsuario.Usuario[]> selectAll_UsuarioAsync() {
            return base.Channel.selectAll_UsuarioAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceUsuario.ResponseBD add_Usuario(BARBARES_SistemaWeb.ServiceReferenceUsuario.Usuario t) {
            return base.Channel.add_Usuario(t);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceUsuario.ResponseBD> add_UsuarioAsync(BARBARES_SistemaWeb.ServiceReferenceUsuario.Usuario t) {
            return base.Channel.add_UsuarioAsync(t);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceUsuario.LogUsuario[] selectAll_LogUsuario() {
            return base.Channel.selectAll_LogUsuario();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceUsuario.LogUsuario[]> selectAll_LogUsuarioAsync() {
            return base.Channel.selectAll_LogUsuarioAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceUsuario.ResponseBD add_LogUsuario(BARBARES_SistemaWeb.ServiceReferenceUsuario.LogUsuario t) {
            return base.Channel.add_LogUsuario(t);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceUsuario.ResponseBD> add_LogUsuarioAsync(BARBARES_SistemaWeb.ServiceReferenceUsuario.LogUsuario t) {
            return base.Channel.add_LogUsuarioAsync(t);
        }
    }
}
