//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BARBARES_SistemaWeb.ServiceReferencePedido {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CuantoPagaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAlmacenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCarritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadoPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMedioPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMotivoCancelacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTiendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VueltoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CuantoPaga {
            get {
                return this.CuantoPagaField;
            }
            set {
                if ((this.CuantoPagaField.Equals(value) != true)) {
                    this.CuantoPagaField = value;
                    this.RaisePropertyChanged("CuantoPaga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEntrega {
            get {
                return this.FechaEntregaField;
            }
            set {
                if ((this.FechaEntregaField.Equals(value) != true)) {
                    this.FechaEntregaField = value;
                    this.RaisePropertyChanged("FechaEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPago {
            get {
                return this.FechaPagoField;
            }
            set {
                if ((this.FechaPagoField.Equals(value) != true)) {
                    this.FechaPagoField = value;
                    this.RaisePropertyChanged("FechaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAlmacen {
            get {
                return this.IdAlmacenField;
            }
            set {
                if ((this.IdAlmacenField.Equals(value) != true)) {
                    this.IdAlmacenField = value;
                    this.RaisePropertyChanged("IdAlmacen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCarrito {
            get {
                return this.IdCarritoField;
            }
            set {
                if ((this.IdCarritoField.Equals(value) != true)) {
                    this.IdCarritoField = value;
                    this.RaisePropertyChanged("IdCarrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDireccion {
            get {
                return this.IdDireccionField;
            }
            set {
                if ((this.IdDireccionField.Equals(value) != true)) {
                    this.IdDireccionField = value;
                    this.RaisePropertyChanged("IdDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstadoPedido {
            get {
                return this.IdEstadoPedidoField;
            }
            set {
                if ((this.IdEstadoPedidoField.Equals(value) != true)) {
                    this.IdEstadoPedidoField = value;
                    this.RaisePropertyChanged("IdEstadoPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMedioPago {
            get {
                return this.IdMedioPagoField;
            }
            set {
                if ((this.IdMedioPagoField.Equals(value) != true)) {
                    this.IdMedioPagoField = value;
                    this.RaisePropertyChanged("IdMedioPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMoneda {
            get {
                return this.IdMonedaField;
            }
            set {
                if ((this.IdMonedaField.Equals(value) != true)) {
                    this.IdMonedaField = value;
                    this.RaisePropertyChanged("IdMoneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMotivoCancelacion {
            get {
                return this.IdMotivoCancelacionField;
            }
            set {
                if ((this.IdMotivoCancelacionField.Equals(value) != true)) {
                    this.IdMotivoCancelacionField = value;
                    this.RaisePropertyChanged("IdMotivoCancelacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPedido {
            get {
                return this.IdPedidoField;
            }
            set {
                if ((this.IdPedidoField.Equals(value) != true)) {
                    this.IdPedidoField = value;
                    this.RaisePropertyChanged("IdPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPersona {
            get {
                return this.IdPersonaField;
            }
            set {
                if ((this.IdPersonaField.Equals(value) != true)) {
                    this.IdPersonaField = value;
                    this.RaisePropertyChanged("IdPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTienda {
            get {
                return this.IdTiendaField;
            }
            set {
                if ((this.IdTiendaField.Equals(value) != true)) {
                    this.IdTiendaField = value;
                    this.RaisePropertyChanged("IdTienda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Vuelto {
            get {
                return this.VueltoField;
            }
            set {
                if ((this.VueltoField.Equals(value) != true)) {
                    this.VueltoField = value;
                    this.RaisePropertyChanged("Vuelto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBD", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ResponseBD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlujoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flujo {
            get {
                return this.FlujoField;
            }
            set {
                if ((object.ReferenceEquals(this.FlujoField, value) != true)) {
                    this.FlujoField = value;
                    this.RaisePropertyChanged("Flujo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetallePedido", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class DetallePedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDetallePedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPromocionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SubtotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDetallePedido {
            get {
                return this.IdDetallePedidoField;
            }
            set {
                if ((this.IdDetallePedidoField.Equals(value) != true)) {
                    this.IdDetallePedidoField = value;
                    this.RaisePropertyChanged("IdDetallePedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPedido {
            get {
                return this.IdPedidoField;
            }
            set {
                if ((this.IdPedidoField.Equals(value) != true)) {
                    this.IdPedidoField = value;
                    this.RaisePropertyChanged("IdPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPromocion {
            get {
                return this.IdPromocionField;
            }
            set {
                if ((this.IdPromocionField.Equals(value) != true)) {
                    this.IdPromocionField = value;
                    this.RaisePropertyChanged("IdPromocion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Subtotal {
            get {
                return this.SubtotalField;
            }
            set {
                if ((this.SubtotalField.Equals(value) != true)) {
                    this.SubtotalField = value;
                    this.RaisePropertyChanged("Subtotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoPedido", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class EstadoPedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadoPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstadoPedido {
            get {
                return this.IdEstadoPedidoField;
            }
            set {
                if ((this.IdEstadoPedidoField.Equals(value) != true)) {
                    this.IdEstadoPedidoField = value;
                    this.RaisePropertyChanged("IdEstadoPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MotivoCancelacion", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class MotivoCancelacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMotivoCancelacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMotivoCancelacion {
            get {
                return this.IdMotivoCancelacionField;
            }
            set {
                if ((this.IdMotivoCancelacionField.Equals(value) != true)) {
                    this.IdMotivoCancelacionField = value;
                    this.RaisePropertyChanged("IdMotivoCancelacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePedido.IPedido_Services")]
    public interface IPedido_Services {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido_Services/selectAll_Pedido", ReplyAction="http://tempuri.org/IPedido_Services/selectAll_PedidoResponse")]
        BARBARES_SistemaWeb.ServiceReferencePedido.Pedido[] selectAll_Pedido();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido_Services/selectAll_Pedido", ReplyAction="http://tempuri.org/IPedido_Services/selectAll_PedidoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePedido.Pedido[]> selectAll_PedidoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido_Services/add_Pedido", ReplyAction="http://tempuri.org/IPedido_Services/add_PedidoResponse")]
        BARBARES_SistemaWeb.ServiceReferencePedido.ResponseBD add_Pedido(BARBARES_SistemaWeb.ServiceReferencePedido.Pedido p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido_Services/add_Pedido", ReplyAction="http://tempuri.org/IPedido_Services/add_PedidoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePedido.ResponseBD> add_PedidoAsync(BARBARES_SistemaWeb.ServiceReferencePedido.Pedido p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido_Services/selectAll_DetallePedido", ReplyAction="http://tempuri.org/IPedido_Services/selectAll_DetallePedidoResponse")]
        BARBARES_SistemaWeb.ServiceReferencePedido.DetallePedido[] selectAll_DetallePedido();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido_Services/selectAll_DetallePedido", ReplyAction="http://tempuri.org/IPedido_Services/selectAll_DetallePedidoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePedido.DetallePedido[]> selectAll_DetallePedidoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido_Services/add_DetallePedido", ReplyAction="http://tempuri.org/IPedido_Services/add_DetallePedidoResponse")]
        BARBARES_SistemaWeb.ServiceReferencePedido.ResponseBD add_DetallePedido(BARBARES_SistemaWeb.ServiceReferencePedido.DetallePedido d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido_Services/add_DetallePedido", ReplyAction="http://tempuri.org/IPedido_Services/add_DetallePedidoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePedido.ResponseBD> add_DetallePedidoAsync(BARBARES_SistemaWeb.ServiceReferencePedido.DetallePedido d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido_Services/selectAll_EstadoPedido", ReplyAction="http://tempuri.org/IPedido_Services/selectAll_EstadoPedidoResponse")]
        BARBARES_SistemaWeb.ServiceReferencePedido.EstadoPedido[] selectAll_EstadoPedido();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido_Services/selectAll_EstadoPedido", ReplyAction="http://tempuri.org/IPedido_Services/selectAll_EstadoPedidoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePedido.EstadoPedido[]> selectAll_EstadoPedidoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido_Services/add_EstadoPedido", ReplyAction="http://tempuri.org/IPedido_Services/add_EstadoPedidoResponse")]
        BARBARES_SistemaWeb.ServiceReferencePedido.ResponseBD add_EstadoPedido(BARBARES_SistemaWeb.ServiceReferencePedido.EstadoPedido e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido_Services/add_EstadoPedido", ReplyAction="http://tempuri.org/IPedido_Services/add_EstadoPedidoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePedido.ResponseBD> add_EstadoPedidoAsync(BARBARES_SistemaWeb.ServiceReferencePedido.EstadoPedido e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido_Services/selectAll_MotivoCancelacion", ReplyAction="http://tempuri.org/IPedido_Services/selectAll_MotivoCancelacionResponse")]
        BARBARES_SistemaWeb.ServiceReferencePedido.MotivoCancelacion[] selectAll_MotivoCancelacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido_Services/selectAll_MotivoCancelacion", ReplyAction="http://tempuri.org/IPedido_Services/selectAll_MotivoCancelacionResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePedido.MotivoCancelacion[]> selectAll_MotivoCancelacionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido_Services/add_MotivoCancelacion", ReplyAction="http://tempuri.org/IPedido_Services/add_MotivoCancelacionResponse")]
        BARBARES_SistemaWeb.ServiceReferencePedido.ResponseBD add_MotivoCancelacion(BARBARES_SistemaWeb.ServiceReferencePedido.MotivoCancelacion m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido_Services/add_MotivoCancelacion", ReplyAction="http://tempuri.org/IPedido_Services/add_MotivoCancelacionResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePedido.ResponseBD> add_MotivoCancelacionAsync(BARBARES_SistemaWeb.ServiceReferencePedido.MotivoCancelacion m);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedido_ServicesChannel : BARBARES_SistemaWeb.ServiceReferencePedido.IPedido_Services, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Pedido_ServicesClient : System.ServiceModel.ClientBase<BARBARES_SistemaWeb.ServiceReferencePedido.IPedido_Services>, BARBARES_SistemaWeb.ServiceReferencePedido.IPedido_Services {
        
        public Pedido_ServicesClient() {
        }
        
        public Pedido_ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Pedido_ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Pedido_ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Pedido_ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePedido.Pedido[] selectAll_Pedido() {
            return base.Channel.selectAll_Pedido();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePedido.Pedido[]> selectAll_PedidoAsync() {
            return base.Channel.selectAll_PedidoAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePedido.ResponseBD add_Pedido(BARBARES_SistemaWeb.ServiceReferencePedido.Pedido p) {
            return base.Channel.add_Pedido(p);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePedido.ResponseBD> add_PedidoAsync(BARBARES_SistemaWeb.ServiceReferencePedido.Pedido p) {
            return base.Channel.add_PedidoAsync(p);
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePedido.DetallePedido[] selectAll_DetallePedido() {
            return base.Channel.selectAll_DetallePedido();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePedido.DetallePedido[]> selectAll_DetallePedidoAsync() {
            return base.Channel.selectAll_DetallePedidoAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePedido.ResponseBD add_DetallePedido(BARBARES_SistemaWeb.ServiceReferencePedido.DetallePedido d) {
            return base.Channel.add_DetallePedido(d);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePedido.ResponseBD> add_DetallePedidoAsync(BARBARES_SistemaWeb.ServiceReferencePedido.DetallePedido d) {
            return base.Channel.add_DetallePedidoAsync(d);
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePedido.EstadoPedido[] selectAll_EstadoPedido() {
            return base.Channel.selectAll_EstadoPedido();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePedido.EstadoPedido[]> selectAll_EstadoPedidoAsync() {
            return base.Channel.selectAll_EstadoPedidoAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePedido.ResponseBD add_EstadoPedido(BARBARES_SistemaWeb.ServiceReferencePedido.EstadoPedido e) {
            return base.Channel.add_EstadoPedido(e);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePedido.ResponseBD> add_EstadoPedidoAsync(BARBARES_SistemaWeb.ServiceReferencePedido.EstadoPedido e) {
            return base.Channel.add_EstadoPedidoAsync(e);
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePedido.MotivoCancelacion[] selectAll_MotivoCancelacion() {
            return base.Channel.selectAll_MotivoCancelacion();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePedido.MotivoCancelacion[]> selectAll_MotivoCancelacionAsync() {
            return base.Channel.selectAll_MotivoCancelacionAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePedido.ResponseBD add_MotivoCancelacion(BARBARES_SistemaWeb.ServiceReferencePedido.MotivoCancelacion m) {
            return base.Channel.add_MotivoCancelacion(m);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePedido.ResponseBD> add_MotivoCancelacionAsync(BARBARES_SistemaWeb.ServiceReferencePedido.MotivoCancelacion m) {
            return base.Channel.add_MotivoCancelacionAsync(m);
        }
    }
}
