//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BARBARES_SistemaWeb.ServiceReferencePersona {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((this.CelularField.Equals(value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDireccion {
            get {
                return this.IdDireccionField;
            }
            set {
                if ((this.IdDireccionField.Equals(value) != true)) {
                    this.IdDireccionField = value;
                    this.RaisePropertyChanged("IdDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPersona {
            get {
                return this.IdPersonaField;
            }
            set {
                if ((this.IdPersonaField.Equals(value) != true)) {
                    this.IdPersonaField = value;
                    this.RaisePropertyChanged("IdPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoDocumento {
            get {
                return this.IdTipoDocumentoField;
            }
            set {
                if ((this.IdTipoDocumentoField.Equals(value) != true)) {
                    this.IdTipoDocumentoField = value;
                    this.RaisePropertyChanged("IdTipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoPersona {
            get {
                return this.IdTipoPersonaField;
            }
            set {
                if ((this.IdTipoPersonaField.Equals(value) != true)) {
                    this.IdTipoPersonaField = value;
                    this.RaisePropertyChanged("IdTipoPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroDocumento {
            get {
                return this.NumeroDocumentoField;
            }
            set {
                if ((this.NumeroDocumentoField.Equals(value) != true)) {
                    this.NumeroDocumentoField = value;
                    this.RaisePropertyChanged("NumeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((this.TelefonoField.Equals(value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBD", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ResponseBD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlujoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flujo {
            get {
                return this.FlujoField;
            }
            set {
                if ((object.ReferenceEquals(this.FlujoField, value) != true)) {
                    this.FlujoField = value;
                    this.RaisePropertyChanged("Flujo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPersona", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class TipoPersona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoPersona {
            get {
                return this.IdTipoPersonaField;
            }
            set {
                if ((this.IdTipoPersonaField.Equals(value) != true)) {
                    this.IdTipoPersonaField = value;
                    this.RaisePropertyChanged("IdTipoPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDocumento", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class TipoDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoDocumento {
            get {
                return this.IdTipoDocumentoField;
            }
            set {
                if ((this.IdTipoDocumentoField.Equals(value) != true)) {
                    this.IdTipoDocumentoField = value;
                    this.RaisePropertyChanged("IdTipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePersona.IPersona_Services")]
    public interface IPersona_Services {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersona_Services/selectAll_Persona", ReplyAction="http://tempuri.org/IPersona_Services/selectAll_PersonaResponse")]
        BARBARES_SistemaWeb.ServiceReferencePersona.Persona[] selectAll_Persona();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersona_Services/selectAll_Persona", ReplyAction="http://tempuri.org/IPersona_Services/selectAll_PersonaResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePersona.Persona[]> selectAll_PersonaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersona_Services/selectByTipo_Persona", ReplyAction="http://tempuri.org/IPersona_Services/selectByTipo_PersonaResponse")]
        BARBARES_SistemaWeb.ServiceReferencePersona.Persona[] selectByTipo_Persona(int idTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersona_Services/selectByTipo_Persona", ReplyAction="http://tempuri.org/IPersona_Services/selectByTipo_PersonaResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePersona.Persona[]> selectByTipo_PersonaAsync(int idTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersona_Services/add_Persona", ReplyAction="http://tempuri.org/IPersona_Services/add_PersonaResponse")]
        BARBARES_SistemaWeb.ServiceReferencePersona.ResponseBD add_Persona(BARBARES_SistemaWeb.ServiceReferencePersona.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersona_Services/add_Persona", ReplyAction="http://tempuri.org/IPersona_Services/add_PersonaResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePersona.ResponseBD> add_PersonaAsync(BARBARES_SistemaWeb.ServiceReferencePersona.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersona_Services/selectAll_TipoPersona", ReplyAction="http://tempuri.org/IPersona_Services/selectAll_TipoPersonaResponse")]
        BARBARES_SistemaWeb.ServiceReferencePersona.TipoPersona[] selectAll_TipoPersona();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersona_Services/selectAll_TipoPersona", ReplyAction="http://tempuri.org/IPersona_Services/selectAll_TipoPersonaResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePersona.TipoPersona[]> selectAll_TipoPersonaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersona_Services/add_TipoPersona", ReplyAction="http://tempuri.org/IPersona_Services/add_TipoPersonaResponse")]
        BARBARES_SistemaWeb.ServiceReferencePersona.ResponseBD add_TipoPersona(BARBARES_SistemaWeb.ServiceReferencePersona.TipoPersona t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersona_Services/add_TipoPersona", ReplyAction="http://tempuri.org/IPersona_Services/add_TipoPersonaResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePersona.ResponseBD> add_TipoPersonaAsync(BARBARES_SistemaWeb.ServiceReferencePersona.TipoPersona t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersona_Services/selectAll_TipoDocumento", ReplyAction="http://tempuri.org/IPersona_Services/selectAll_TipoDocumentoResponse")]
        BARBARES_SistemaWeb.ServiceReferencePersona.TipoDocumento[] selectAll_TipoDocumento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersona_Services/selectAll_TipoDocumento", ReplyAction="http://tempuri.org/IPersona_Services/selectAll_TipoDocumentoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePersona.TipoDocumento[]> selectAll_TipoDocumentoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersona_Services/add_TipoDocumento", ReplyAction="http://tempuri.org/IPersona_Services/add_TipoDocumentoResponse")]
        BARBARES_SistemaWeb.ServiceReferencePersona.ResponseBD add_TipoDocumento(BARBARES_SistemaWeb.ServiceReferencePersona.TipoDocumento t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersona_Services/add_TipoDocumento", ReplyAction="http://tempuri.org/IPersona_Services/add_TipoDocumentoResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePersona.ResponseBD> add_TipoDocumentoAsync(BARBARES_SistemaWeb.ServiceReferencePersona.TipoDocumento t);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersona_ServicesChannel : BARBARES_SistemaWeb.ServiceReferencePersona.IPersona_Services, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Persona_ServicesClient : System.ServiceModel.ClientBase<BARBARES_SistemaWeb.ServiceReferencePersona.IPersona_Services>, BARBARES_SistemaWeb.ServiceReferencePersona.IPersona_Services {
        
        public Persona_ServicesClient() {
        }
        
        public Persona_ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Persona_ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Persona_ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Persona_ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePersona.Persona[] selectAll_Persona() {
            return base.Channel.selectAll_Persona();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePersona.Persona[]> selectAll_PersonaAsync() {
            return base.Channel.selectAll_PersonaAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePersona.Persona[] selectByTipo_Persona(int idTipo) {
            return base.Channel.selectByTipo_Persona(idTipo);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePersona.Persona[]> selectByTipo_PersonaAsync(int idTipo) {
            return base.Channel.selectByTipo_PersonaAsync(idTipo);
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePersona.ResponseBD add_Persona(BARBARES_SistemaWeb.ServiceReferencePersona.Persona p) {
            return base.Channel.add_Persona(p);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePersona.ResponseBD> add_PersonaAsync(BARBARES_SistemaWeb.ServiceReferencePersona.Persona p) {
            return base.Channel.add_PersonaAsync(p);
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePersona.TipoPersona[] selectAll_TipoPersona() {
            return base.Channel.selectAll_TipoPersona();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePersona.TipoPersona[]> selectAll_TipoPersonaAsync() {
            return base.Channel.selectAll_TipoPersonaAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePersona.ResponseBD add_TipoPersona(BARBARES_SistemaWeb.ServiceReferencePersona.TipoPersona t) {
            return base.Channel.add_TipoPersona(t);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePersona.ResponseBD> add_TipoPersonaAsync(BARBARES_SistemaWeb.ServiceReferencePersona.TipoPersona t) {
            return base.Channel.add_TipoPersonaAsync(t);
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePersona.TipoDocumento[] selectAll_TipoDocumento() {
            return base.Channel.selectAll_TipoDocumento();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePersona.TipoDocumento[]> selectAll_TipoDocumentoAsync() {
            return base.Channel.selectAll_TipoDocumentoAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePersona.ResponseBD add_TipoDocumento(BARBARES_SistemaWeb.ServiceReferencePersona.TipoDocumento t) {
            return base.Channel.add_TipoDocumento(t);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePersona.ResponseBD> add_TipoDocumentoAsync(BARBARES_SistemaWeb.ServiceReferencePersona.TipoDocumento t) {
            return base.Channel.add_TipoDocumentoAsync(t);
        }
    }
}
