//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BARBARES_SistemaWeb.ServiceReferenceParametro {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parametro", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Parametro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdParametroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValorNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPadre {
            get {
                return this.CodigoPadreField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPadreField, value) != true)) {
                    this.CodigoPadreField = value;
                    this.RaisePropertyChanged("CodigoPadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdParametro {
            get {
                return this.IdParametroField;
            }
            set {
                if ((this.IdParametroField.Equals(value) != true)) {
                    this.IdParametroField = value;
                    this.RaisePropertyChanged("IdParametro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ValorNum {
            get {
                return this.ValorNumField;
            }
            set {
                if ((this.ValorNumField.Equals(value) != true)) {
                    this.ValorNumField = value;
                    this.RaisePropertyChanged("ValorNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBD", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ResponseBD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlujoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flujo {
            get {
                return this.FlujoField;
            }
            set {
                if ((object.ReferenceEquals(this.FlujoField, value) != true)) {
                    this.FlujoField = value;
                    this.RaisePropertyChanged("Flujo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParametrosSeguridad", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ParametrosSeguridad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadIntentosFallidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaracteresContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdParametrosSeguridadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LongitudContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TiempoMaximoSesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TiempoVigenciaDiasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadIntentosFallidos {
            get {
                return this.CantidadIntentosFallidosField;
            }
            set {
                if ((this.CantidadIntentosFallidosField.Equals(value) != true)) {
                    this.CantidadIntentosFallidosField = value;
                    this.RaisePropertyChanged("CantidadIntentosFallidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaracteresContrasena {
            get {
                return this.CaracteresContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.CaracteresContrasenaField, value) != true)) {
                    this.CaracteresContrasenaField = value;
                    this.RaisePropertyChanged("CaracteresContrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdParametrosSeguridad {
            get {
                return this.IdParametrosSeguridadField;
            }
            set {
                if ((this.IdParametrosSeguridadField.Equals(value) != true)) {
                    this.IdParametrosSeguridadField = value;
                    this.RaisePropertyChanged("IdParametrosSeguridad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LongitudContrasena {
            get {
                return this.LongitudContrasenaField;
            }
            set {
                if ((this.LongitudContrasenaField.Equals(value) != true)) {
                    this.LongitudContrasenaField = value;
                    this.RaisePropertyChanged("LongitudContrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TiempoMaximoSesion {
            get {
                return this.TiempoMaximoSesionField;
            }
            set {
                if ((this.TiempoMaximoSesionField.Equals(value) != true)) {
                    this.TiempoMaximoSesionField = value;
                    this.RaisePropertyChanged("TiempoMaximoSesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TiempoVigenciaDias {
            get {
                return this.TiempoVigenciaDiasField;
            }
            set {
                if ((this.TiempoVigenciaDiasField.Equals(value) != true)) {
                    this.TiempoVigenciaDiasField = value;
                    this.RaisePropertyChanged("TiempoVigenciaDias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceParametro.IParametro_Services")]
    public interface IParametro_Services {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametro_Services/add_Parametro", ReplyAction="http://tempuri.org/IParametro_Services/add_ParametroResponse")]
        BARBARES_SistemaWeb.ServiceReferenceParametro.ResponseBD add_Parametro(BARBARES_SistemaWeb.ServiceReferenceParametro.Parametro p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametro_Services/add_Parametro", ReplyAction="http://tempuri.org/IParametro_Services/add_ParametroResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceParametro.ResponseBD> add_ParametroAsync(BARBARES_SistemaWeb.ServiceReferenceParametro.Parametro p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametro_Services/selectAll_Parametro", ReplyAction="http://tempuri.org/IParametro_Services/selectAll_ParametroResponse")]
        BARBARES_SistemaWeb.ServiceReferenceParametro.Parametro[] selectAll_Parametro();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametro_Services/selectAll_Parametro", ReplyAction="http://tempuri.org/IParametro_Services/selectAll_ParametroResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceParametro.Parametro[]> selectAll_ParametroAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametro_Services/selectAll_ParametrosSeguridad", ReplyAction="http://tempuri.org/IParametro_Services/selectAll_ParametrosSeguridadResponse")]
        BARBARES_SistemaWeb.ServiceReferenceParametro.ParametrosSeguridad[] selectAll_ParametrosSeguridad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametro_Services/selectAll_ParametrosSeguridad", ReplyAction="http://tempuri.org/IParametro_Services/selectAll_ParametrosSeguridadResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceParametro.ParametrosSeguridad[]> selectAll_ParametrosSeguridadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametro_Services/add_ParametrosSeguridad", ReplyAction="http://tempuri.org/IParametro_Services/add_ParametrosSeguridadResponse")]
        BARBARES_SistemaWeb.ServiceReferenceParametro.ResponseBD add_ParametrosSeguridad(BARBARES_SistemaWeb.ServiceReferenceParametro.ParametrosSeguridad p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametro_Services/add_ParametrosSeguridad", ReplyAction="http://tempuri.org/IParametro_Services/add_ParametrosSeguridadResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceParametro.ResponseBD> add_ParametrosSeguridadAsync(BARBARES_SistemaWeb.ServiceReferenceParametro.ParametrosSeguridad p);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IParametro_ServicesChannel : BARBARES_SistemaWeb.ServiceReferenceParametro.IParametro_Services, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Parametro_ServicesClient : System.ServiceModel.ClientBase<BARBARES_SistemaWeb.ServiceReferenceParametro.IParametro_Services>, BARBARES_SistemaWeb.ServiceReferenceParametro.IParametro_Services {
        
        public Parametro_ServicesClient() {
        }
        
        public Parametro_ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Parametro_ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Parametro_ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Parametro_ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceParametro.ResponseBD add_Parametro(BARBARES_SistemaWeb.ServiceReferenceParametro.Parametro p) {
            return base.Channel.add_Parametro(p);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceParametro.ResponseBD> add_ParametroAsync(BARBARES_SistemaWeb.ServiceReferenceParametro.Parametro p) {
            return base.Channel.add_ParametroAsync(p);
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceParametro.Parametro[] selectAll_Parametro() {
            return base.Channel.selectAll_Parametro();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceParametro.Parametro[]> selectAll_ParametroAsync() {
            return base.Channel.selectAll_ParametroAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceParametro.ParametrosSeguridad[] selectAll_ParametrosSeguridad() {
            return base.Channel.selectAll_ParametrosSeguridad();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceParametro.ParametrosSeguridad[]> selectAll_ParametrosSeguridadAsync() {
            return base.Channel.selectAll_ParametrosSeguridadAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferenceParametro.ResponseBD add_ParametrosSeguridad(BARBARES_SistemaWeb.ServiceReferenceParametro.ParametrosSeguridad p) {
            return base.Channel.add_ParametrosSeguridad(p);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferenceParametro.ResponseBD> add_ParametrosSeguridadAsync(BARBARES_SistemaWeb.ServiceReferenceParametro.ParametrosSeguridad p) {
            return base.Channel.add_ParametrosSeguridadAsync(p);
        }
    }
}
