//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BARBARES_SistemaWeb.ServiceReferencePerfil {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Perfil", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Perfil : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPerfil {
            get {
                return this.IdPerfilField;
            }
            set {
                if ((this.IdPerfilField.Equals(value) != true)) {
                    this.IdPerfilField = value;
                    this.RaisePropertyChanged("IdPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBD", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ResponseBD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlujoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flujo {
            get {
                return this.FlujoField;
            }
            set {
                if ((object.ReferenceEquals(this.FlujoField, value) != true)) {
                    this.FlujoField = value;
                    this.RaisePropertyChanged("Flujo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerfilXUsuario", Namespace="http://schemas.datacontract.org/2004/07/BARABARES_Services.DTO")]
    [System.SerializableAttribute()]
    public partial class PerfilXUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaAsignacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPerfilXUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaAsignacion {
            get {
                return this.FechaAsignacionField;
            }
            set {
                if ((this.FechaAsignacionField.Equals(value) != true)) {
                    this.FechaAsignacionField = value;
                    this.RaisePropertyChanged("FechaAsignacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPerfil {
            get {
                return this.IdPerfilField;
            }
            set {
                if ((this.IdPerfilField.Equals(value) != true)) {
                    this.IdPerfilField = value;
                    this.RaisePropertyChanged("IdPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPerfilXUsuario {
            get {
                return this.IdPerfilXUsuarioField;
            }
            set {
                if ((this.IdPerfilXUsuarioField.Equals(value) != true)) {
                    this.IdPerfilXUsuarioField = value;
                    this.RaisePropertyChanged("IdPerfilXUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePerfil.IPerfil_Services")]
    public interface IPerfil_Services {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfil_Services/selectAll_Perfil", ReplyAction="http://tempuri.org/IPerfil_Services/selectAll_PerfilResponse")]
        BARBARES_SistemaWeb.ServiceReferencePerfil.Perfil[] selectAll_Perfil();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfil_Services/selectAll_Perfil", ReplyAction="http://tempuri.org/IPerfil_Services/selectAll_PerfilResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePerfil.Perfil[]> selectAll_PerfilAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfil_Services/add_Perfil", ReplyAction="http://tempuri.org/IPerfil_Services/add_PerfilResponse")]
        BARBARES_SistemaWeb.ServiceReferencePerfil.ResponseBD add_Perfil(BARBARES_SistemaWeb.ServiceReferencePerfil.Perfil p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfil_Services/add_Perfil", ReplyAction="http://tempuri.org/IPerfil_Services/add_PerfilResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePerfil.ResponseBD> add_PerfilAsync(BARBARES_SistemaWeb.ServiceReferencePerfil.Perfil p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfil_Services/selectAll_PerfilXUsuario", ReplyAction="http://tempuri.org/IPerfil_Services/selectAll_PerfilXUsuarioResponse")]
        BARBARES_SistemaWeb.ServiceReferencePerfil.PerfilXUsuario[] selectAll_PerfilXUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfil_Services/selectAll_PerfilXUsuario", ReplyAction="http://tempuri.org/IPerfil_Services/selectAll_PerfilXUsuarioResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePerfil.PerfilXUsuario[]> selectAll_PerfilXUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfil_Services/add_PerfilXUsuario", ReplyAction="http://tempuri.org/IPerfil_Services/add_PerfilXUsuarioResponse")]
        BARBARES_SistemaWeb.ServiceReferencePerfil.ResponseBD add_PerfilXUsuario(BARBARES_SistemaWeb.ServiceReferencePerfil.PerfilXUsuario m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfil_Services/add_PerfilXUsuario", ReplyAction="http://tempuri.org/IPerfil_Services/add_PerfilXUsuarioResponse")]
        System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePerfil.ResponseBD> add_PerfilXUsuarioAsync(BARBARES_SistemaWeb.ServiceReferencePerfil.PerfilXUsuario m);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPerfil_ServicesChannel : BARBARES_SistemaWeb.ServiceReferencePerfil.IPerfil_Services, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Perfil_ServicesClient : System.ServiceModel.ClientBase<BARBARES_SistemaWeb.ServiceReferencePerfil.IPerfil_Services>, BARBARES_SistemaWeb.ServiceReferencePerfil.IPerfil_Services {
        
        public Perfil_ServicesClient() {
        }
        
        public Perfil_ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Perfil_ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Perfil_ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Perfil_ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePerfil.Perfil[] selectAll_Perfil() {
            return base.Channel.selectAll_Perfil();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePerfil.Perfil[]> selectAll_PerfilAsync() {
            return base.Channel.selectAll_PerfilAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePerfil.ResponseBD add_Perfil(BARBARES_SistemaWeb.ServiceReferencePerfil.Perfil p) {
            return base.Channel.add_Perfil(p);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePerfil.ResponseBD> add_PerfilAsync(BARBARES_SistemaWeb.ServiceReferencePerfil.Perfil p) {
            return base.Channel.add_PerfilAsync(p);
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePerfil.PerfilXUsuario[] selectAll_PerfilXUsuario() {
            return base.Channel.selectAll_PerfilXUsuario();
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePerfil.PerfilXUsuario[]> selectAll_PerfilXUsuarioAsync() {
            return base.Channel.selectAll_PerfilXUsuarioAsync();
        }
        
        public BARBARES_SistemaWeb.ServiceReferencePerfil.ResponseBD add_PerfilXUsuario(BARBARES_SistemaWeb.ServiceReferencePerfil.PerfilXUsuario m) {
            return base.Channel.add_PerfilXUsuario(m);
        }
        
        public System.Threading.Tasks.Task<BARBARES_SistemaWeb.ServiceReferencePerfil.ResponseBD> add_PerfilXUsuarioAsync(BARBARES_SistemaWeb.ServiceReferencePerfil.PerfilXUsuario m) {
            return base.Channel.add_PerfilXUsuarioAsync(m);
        }
    }
}
